base/urls.py
from django.urls import path,re_path
from . import views

urlpatterns = [
    path('initialisation',views.initialisation,name='initialisation'),
    path('gestion_generale',views.gestion_generale,name='gestion_generale'),
    path('modif_creneaux',views.modif_creneaux,name='modif_creneaux'),
    path('creation_creneaux',views.creation_creneaux,name='creation_creneaux'),
    path('inscrits',views.inscrits,name='inscrits'),
    path('recapitulatif',views.recapitulatif,name='recapitulatif'),
    path('gestion_creneaux',views.gestion_creneaux,name='gestion_creneaux'),
    path('coordonnees',views.coordonnees,name='coordonnees'),
    path('connexion',views.connexion,name='connexion'),
    path('deconnexion',views.deconnexion,name='deconnexion'),
    path('recuperation_password',views.recuperation_password,name='recuperation_password'),
    path('recuperation_login',views.recuperation_login,name='recuperation_login'),
    path('creation_compte',views.creation_compte,name='creation_compte'),
    path('validation_compte/<str:login>/<str:lehash>',views.validation_compte,name='validation_compte'),
    re_path(r'validation_comptea*',views.validation_compte,name='validation_compte_erreur'),
    path('demande_reinitialisation/<str:login>/<str:lehash>',views.demande_reinitialisation,name='demande_reinitialisation'),
    re_path(r'demande_reinitialisationa*',views.demande_reinitialisation,name='demande_reinitialisation_erreur'),
    path('reglages',views.reglages,name='reglages'),
    path('informations',views.informations,name='informations'),
    path('stats',views.stats,name='stats'),
    path('recupere_stats',views.recupere_stats,name='recupere_stats'),
    re_path(r'a*', views.creneaux,name='creneaux'),   
]


gestioncreneaux/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import Group, User

class Utilisateur(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=30)
    date_demande=models.DateField(null=True)
    csrf_token=models.TextField(null=True)
    en_attente_confirmation=models.BooleanField(default=True) # lien envoyé et non validé par mail
    reinitialisation_password=models.BooleanField(default=False)
    information=models.BooleanField(default=True)

class Creneaux(models.Model):
    date=models.DateField()
    intitulé=models.CharField(max_length=100)
    text_bouton=models.CharField(max_length=100,default="")
    type_creneau=models.IntegerField(default=0)
    # 0 : créneau classique
    # 1 : avec inscription
    # 2 : avec lien html
    lien=models.CharField(max_length=100,default="",blank=True)
    staff=models.IntegerField(default=0,blank=True)

class Inscription(models.Model):
    idcreneau=models.ForeignKey(Creneaux,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    commentaire=models.CharField(max_length=100)
    statut=models.CharField(max_length=50,default="")

class Autorisation(models.Model):
    idcreneau=models.ForeignKey(Creneaux,on_delete=models.CASCADE)
    groupe=models.ForeignKey(Group,on_delete=models.CASCADE)

class Textes(models.Model):
    nom=models.CharField(max_length=50)
    contenu=models.TextField()

base/forms.py
from django.forms import ModelForm
from .models import *

class CreneauxForm(ModelForm):
    class Meta:
        model=Creneaux
        fields='__all__'

class AutorisationForm(ModelForm):
    class Meta:
        model=Autorisation
        fields='__all__'

base/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout,authenticate, login
from django.http import HttpResponse
import json

from gestioncreneaux.settings import SECURE_SSL_REDIRECT
from .fonctions import *
from .forms import *

# A FAIRE !!!!!!!!!!!!
# - connexion : se débrouiller pour revenir sur la bonne page :
#     soit selon le groupe, soit selon la page(à enregistrer) d'appel de connexion
# - réglage : afficher le bon menu et pas celui d'un simple utilisateur, si staff/admin? anecdotique
# - si le statut du créneau change : inscription/non : supprimer les inscrits?
# - nettoyer la base avec les comptes non validés au bout d'un moment?
#  - enlever les fonctions menus en trop une fois que c'est bien géré
# # !!!!!!!!!!!!!!!!!!!!!!

# décorateur pour vérifier si le groupe de l'utilisateur est dans la liste
# renvoie vers la page de connexion sinon
# pas d'arguments (ou liste vide) si on veut juste un utilisateur quelconque connecté
def auth(group_list=[]):
    def teste(func):
        def nouvelle_func(request,*args,**kwargs):
            if request.user.is_authenticated:
                if group_list==[]:
                    return func(request,*args,**kwargs)
                lesgroupes=request.user.groups.all()
                for x in group_list:
                    if x in lesgroupes:
                        return func(request,*args,**kwargs)
            return connexion(request)
        return nouvelle_func
    return teste

# pages générales pour tout le monde
def creneaux(request):
    if request.method=='POST':
        statut=est_staff(request)
        if request.user.is_authenticated:
            click_creneau(request)
            response_data = {"creneaux":json_creneaux(request),
            "inscription":json_inscription(request),"statut" : statut}
        else:
            if ("avecclick" in request.POST) and (request.POST["avecclick"]=="true"):
                # on redirigera vers la page de connexion 
                response_data={"demande" : "creneaux"}
            else:
                response_data={"creneaux":json_creneaux(request),"inscription" :{},"statut" : statut}
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    context={"menu" : menu_general(request)}
    context["annonce"]=recupere_annonce()
    context["information"]=recupere_information(request)
    return render(request,'base/creneaux.html',context)

def informations(request):
    context={"menu" : menu_general(request)}
    return render(request,'base/informations.html',context)

def connexion(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is not None: 
            # on vérifie si le compte a bien été activé
            try:
                utilisateur=Utilisateur.objects.get(user=user)
                if not utilisateur.en_attente_confirmation:
                    login(request,user)
                    return redirect('creneaux')
                #compte en attente si on arrive ici
            except:
                pass
    context={"menu" : []}
    return render(request,'base/connexion.html',context)

def deconnexion(request):
    logout(request)
    return creneaux(request)

def creation_compte(request):
    context={"menu" : []}
    if request.method=="POST":
        reussi,err=demande_creation_compte(request)
        if reussi:
            context["reussi"]=True
        else:
            context["echec"]=True
            context["err"]=err
            context["ancien"]=request.POST
    return render(request,'base/creation_compte.html',context)

def validation_compte(request,login=None,lehash=None):
    if login==None:
        context={ "msg" : "Le lien n'est pas valide"}
    else:
        context={ "msg" : verifie_lien_validation(login,lehash)}
    return render(request,'base/validation_compte.html',context)

def recuperation_password(request):
    context={}
    if request.method=="POST":   
        context["msg"]=envoie_mail_recuperation_mot_de_passe(request)
    return render(request,'base/recuperation_password.html',context)

def recuperation_login(request):
    context={}
    if request.method=="POST":   
        context["msg"]=envoie_mail_recuperation_login(request)
    return render(request,'base/recuperation_login.html',context)

def demande_reinitialisation(request,login=None,lehash=None):
    if request.method=='POST':
        print("here")
        context={**reinitialise_mot_de_passe(request)}
    elif login==None:
        context={ "msg" : "Le lien n'est pas valide"}
    else:
        context={ **verifie_lien_reinitialisation(login,lehash)}
    return render(request,'base/demande_reinitialisation.html',context)

# pages générales si connecté
@auth()
def reglages(request):
    context={"menu" : menu_general(request)}
    if request.method=="POST":
        if 'action' in request.POST:
            if request.POST['action']=='change password':
                context["msg"]=change_mot_de_passe(request)
            if request.POST['action']=='reglages':
                context["msg"]=change_reglages(request)
    recupere_reglages(request,context)
    return render(request,'base/reglages.html',context)

# pages accessibles au staff
@auth([groupe_staff])
def gestion_creneaux(request):
    if request.method=='POST':
        click_staff(request)
        response_data = {"creneaux":json_creneaux(request,tous=True),
        "inscription":json_inscription(request,staff=True)}
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    context={"menu" : menu_staff(request)}
    return render(request,'base/gestion_creneaux.html',context)

@auth([groupe_staff])
def recapitulatif(request):
    context={"menu" : menu_staff(request)}
    context["creneau_et_staff"]=creneau_et_staff()
    return render(request,'base/recapitulatif.html',context)

@auth([groupe_staff])
def coordonnees(request):
    context={"menu" : menu_staff(request),"lestaff" : recupere_coordonnees_staff()}
    return render(request,'base/coordonnees.html',context)

#pages accessibles aux gestionnaires de créneaux
dico_type_creneau={"libre" : 0 , "inscription" : 1 , "lien" : 2 }
@auth([groupe_gestion_creneaux])
def creation_creneaux(request):
    context={"menu" : menu_gestion(request)}
    if request.method=="POST":
        try:
            new_creneau=Creneaux(date=request.POST["date"],intitulé=request.POST["intitulé"],text_bouton=request.POST["text_bouton"],
                                 lien=request.POST["text_lien"],type_creneau=dico_type_creneau[request.POST["type_creneau"]])
            new_creneau.save()
            autorisation_creneau=Autorisation(idcreneau=new_creneau,groupe=sans_groupe)
            autorisation_creneau.save()
        except:
            pass
    context['creneaux']=joli_date_creneaux(recupere_creneaux(request,tous=True))
    return render(request,'base/creation_creneaux.html',context)

@auth([groupe_gestion_creneaux])
def modif_creneaux(request):
    if request.method=='POST':
        if 'action' in request.POST:
            if request.POST['action']=='supprime':
                supprime_creneau(request.POST) 
            if request.POST['action'] =='modifie':
                modifie_creneau(request.POST)          
        response_data = {"creneaux":json_creneaux(request,tous=True,joli=False)}
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    context={"menu" : menu_gestion(request)}
    return render(request,'base/modif_creneaux.html',context)

@auth([groupe_staff])
def inscrits(request):
    context={"menu" : menu_staff(request), "inscriptions" : recupere_inscrits()}
    return render(request,'base/inscrits.html',context)

#pages accessibles aux gestionnaires avec tous les droits
@auth([groupe_gestion_generale])
def gestion_generale(request):
    res,err=None,""
    if request.method=='POST':
        if 'action' in request.POST:
            if request.POST['action']=='ajout':
                res,err=ajout_compte(request)
            if request.POST['action'] =='modifie':
                res,err=modifie_compte(request)
            if request.POST['action']=='annonce':
                res,err=modifie_annonce(request)
            if request.POST['action']=='information':
                res,err=modifie_information(request)
            if request.POST['action']=='delai':
                res,err=modifie_delai(request)
    try:
        delai=int(Textes.objects.get(nom="delai").contenu)
    except:
        delai=2
    context={"menu" : menu_gestion(request),"lescomptes" : recupere_comptes(),
     "reussi" : res, "err" : err, "annonce" : recupere_txt_annonce(), "delai" : delai,
     "information" : recupere_txt_information() }
    return render(request,'base/gestion_generale.html',context)

@auth([groupe_gestion_generale])
def stats(request):
    context={"menu" : menu_staff(request)}
    #la_liste=creneau_et_staff_ancien()
    #context["staff_en_or"]=ordonne(la_liste)
    #context["creneau_et_staff"]=la_liste
    return render(request,'base/stats.html',context)

@auth([groupe_gestion_generale])
def recupere_stats(request):
    if request.method=='POST' and "fonction" in request.POST and "datedebut" in request.POST and "datefin" in request.POST:
        response_data=recupere_stats_fonction(request.POST["fonction"],request.POST["datedebut"],request.POST["datefin"])
    else:
        response_data={}
    return HttpResponse(json.dumps(response_data), content_type="application/json")    

@auth([groupe_gestion_generale])
def initialisation(request):

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jeu libre SandSystem</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style/style.css' %}">
    <script src="{% static 'js/java.js' %}?=104" ></script> 
</head>

<body>
    {% block body %}

    {% endblock body %}
</body>

</html>

base/templates/base/creation_compte.html
{% extends 'base.html' %}

{% block body %}

{% if reussi %} <span class="cred"><BR> L demande de création a bien été prise en compte.  <BR>
Un mail a été envoyé à l'adresse indiquée pour valider l'inscription <BR><BR></span>
<a href="{% url 'connexion' %}"> Retour à la page de connexion</a> {% else %}
{% if echec %} <BR><span class="cred">Impossible de créer le compte : <BR> {{ err }} </span><BR>{% endif %}
<BR>
<fieldset class="formulaire">
    <legend>Formulaire d'inscription</legend>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="item_formulaire">
            <label for="id_login">Choix du login : </label>
            <input type="text" name="login" maxlength="100" required id="id_login" value="{{ ancien.login }}">
        </div> 
        <div class="item_formulaire">
            <label for="id_prenom">Prénom : </label>
            <input type="text" name="prenom" maxlength="100" required id="id_prenom" value="{{ ancien.prenom }}">
        </div> 
        <div class="item_formulaire">
            <label for="id_nom">Nom : </label>
            <input type="text" name="nom" maxlength="100"  id="id_nom" value="{{ ancien.nom }}">
        </div> 
        <div class="item_formulaire">
            <label for="id_mail">mail : </label>
            <input type="email" name="mail" maxlength="100" required id="id_mail" value="{{ ancien.mail }}">
        </div> 
        <div class="item_formulaire">
            <label for="id_telephone">Téléphone (facultatif) : </label>
            <input type="text" name="telephone" maxlength="100"  id="id_telephone" value="{{ ancien.telephone }}">
        </div> 
        <div class="item_formulaire">
            <label for="id_password">mot de passe : </label>
            <input type="password" name="password" maxlength="100" required id="id_password">
        </div> 
        <div class="item_formulaire">
            <label for="id_password_verif">mot de passe, confirmation : </label>
            <input type="password" name="password_verif" maxlength="100" required id="id_password_verif">
        </div> 
        <input class="round" type="submit" value="Création du compte"/>

    </form>
</fieldset>{% endif %}
{% endblock body %}

base/templates/base/creneaux.html
{% extends 'base.html' %}

{% block body %}
{% csrf_token %}
{% include 'menu.html'%}
<BR> {% for line in annonce %} <p>{{ line }}</p>{% endfor %}
{% if information %} {% for line in information %} <p>{{ line }}</p>{% endfor %} {% endif %}<BR>

<fieldset>
    <legend>Liste des créneaux disponibles : (créneaux sélectionnés en orange)</legend>
    <div class="creneaux" id="creneaux_general">
    </div>
</fieldset>

<script>
    click_creneau(0,false)
</script>
{% endblock body %}

base/templates/base/demande_reinitialisation.html
{% extends 'base.html' %}

{% block body %}
<BR>
{% if not autorise %} <span class="cred">{{ msg }}</span><BR><BR> {% else %}
    <fieldset class="formulaire">
        <legend>Saisir le nouveau mot de passe pour le compte {{ login }}: </legend>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="item_formulaire">
                <label for="password">Nouveau mot de passe : </label>
                <input type="password" name="password" maxlength="100" required id="password">
            </div> 
            <input type="hidden" name="login" value="{{ login }}" />
            <input type="hidden" name="hash" value="{{ hash}}" />            
            <input class="round" type="submit" value="Valider ce nouveau mot de passe"/>
    
        </form>
    </fieldset> <BR> {% endif %}
    <a href="{% url 'creneaux' %}"> Retour à la page d'accueil</a>

{% endblock body %}

base/templates/base/gestion_creneaux.html
{% extends 'base.html' %}

{% block body %}
{% csrf_token %}
{% include 'menu.html'%}

<BR><BR>
    <form id="le_formulaire_index" class="formulaire_index center" method="post" action="index.php">
        <input type="hidden" name="validation" value="">
    <fieldset>
        <legend>Liste des créneaux disponibles : (créneaux sélectionnés en orange)</legend>
    <div class="creneaux_staff" id="creneaux_staff">      
    </div>
    </fieldset><BR>
    </form>

<script>
    click_staff(0,false)
</script>
{% endblock body %}

base/templates/base/gestion_generale.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% include 'menu.html'%}

{% if err %} <span class="cred"><BR>{{ err }} </span>{% endif %}
<BR>
<DIV>
    <FORM  method="post" action="">
        {% csrf_token %}
            <legend class="center">Création d'un compte:</legend><BR>
     <div class="center"> <!-- grid layout on fieldset is buggy on Chrome -->
        <label for="login">Login</label>
        <input id="login" name="login" value="{{ login }}" required/>
        <label for="prenom">Prénom</label>
        <input id="prenom" name="prenom" value="{{ prenom }}" required/>
        <label for="nom">Nom</label>
        <input id="nom" name="nom" value="{{ nom }}"/>
        <label for="mail">Mail</label>
        <input type="email" id="mail" name="mail" value="{{ mail }}" required/>
        <label for="telephone">Téléphone</label>
        <input id="telephone" name="telephone" value="{{ telephone }}"/><BR><BR>
        <label for="id_gr_staff"> Groupe staff ? </label>
        <input type="checkbox" name="gr_staff" id="id_gr_staff" checked>
        <label for="id_gr_gestion"> Groupe gestion créneaux ? </label>
        <input type="checkbox" name="gr_gestion" id="id_gr_gestion">
        <label for="id_gr_admin"> Groupe admin ? </label>
        <input type="checkbox" name="gr_admin" id="id_gr_admin">                
        <label for="password">mot de passe :</label>        
        <input id="password" name="password" value="staff"/>
        <label for="confirmation">confirmation</label>        
        <input id="confirmation" name="confirmation"/>
        <input type="hidden" name="action" value="ajout" /><BR><BR>
        <input class="bouton" type="submit" value="Créer le compte avec ces informations">
    </div>
    </FORM>
</DIV><BR><BR>

<DIV>
    <FORM  method="post" action="">
        {% csrf_token %}
            <legend class="center">Modifier les données de :
            <select id="select" onchange="ajusteDonnees()">{% for key,value in lescomptes.items %}
                <option value="{{ key }}"> {{ value.login }} : {{ value.prenom }} {{ value.nom }}</option>{% endfor %}
            </select> 
            </legend><BR>
     <div class="center"> <!-- grid layout on fieldset is buggy on Chrome -->
        <input type="hidden" id="mpk" name="mpk"/>
        <label for="mprenom">Prénom</label>
        <input id="mprenom" name="mprenom" value="{{ prenom }}" required/>
        <label for="mnom">Nom</label>
        <input id="mnom" name="mnom" value="{{ nom }}"/>
        <label for="mmail">Mail</label>
        <input type="email" id="mmail" name="mmail" value="{{ mail }}" required/>
        <label for="mtelephone">Téléphone</label>
        <input id="mtelephone" name="mtelephone" value="{{ telephone }}"/><BR><BR>
        <label for="mmid_gr_staff"> Groupe staff ? </label>
        <input type="checkbox" name="gr_staff" id="mid_gr_staff">
        <label for="mid_gr_gestion"> Groupe gestion créneaux ? </label>
        <input type="checkbox" name="gr_gestion" id="mid_gr_gestion">
        <label for="mid_gr_admin"> Groupe admin ? </label>
        <input type="checkbox" name="gr_admin" id="mid_gr_admin">                
        <label for="mconfirmation">confirmation</label>        
        <input id="mconfirmation" name="mconfirmation"/>
        <input type="hidden" name="action" value="modifie" />
        <div></div><BR>
        <input class="bouton" type="submit" value="Modifier les données de ce compte">
    </div>
    </FORM>
</DIV>

<div>
    <form method="post" action="">
        {% csrf_token %}
        <legend>Annonce de la page d'accueil :</legend>
        <textarea class="annonce" style="width : 80%;" rows=10 name="annonce">{{ annonce }}
        </textarea>
        <input type="hidden" name="action" value="annonce" /><BR><BR>
        <input class="bouton" type="submit" value="Mettre à jour le texte de l'annonce">
       </form>
</div><BR><BR>

    <div>
        <form method="post" action="">
            {% csrf_token %}
            <legend>Informations de la page d'accueil :</legend>
            <textarea class="annonce" style="width : 80%;" rows=10 name="information">{{ information }}
            </textarea>
            <input type="hidden" name="action" value="information" /><BR><BR>
            <input class="bouton" type="submit" value="Mettre à jour le texte d'informations">
           </form>
    </div><BR><BR>
    
    <div>
        <form method="post" action="">
            {% csrf_token %}
            <legend>Gestion des créneaux sans staff :</legend>
            <label for="delai">Mettre en rouge s'il n'y a pas de staff pour gérer </label>        
            <input id="delai" name="delai" size="2" value="{{ delai }}"/>  jours avant le créneau          
            <input type="hidden" name="action" value="delai" />
            <input class="bouton" type="submit" value="Mettre à jour la durée">
           </form>
    </div>
<BR><BR>

<script src="{% static 'js/java_admin_generale.js' %}" ></script>
<script>
    lescomptes={ {% for key,value in lescomptes.items %} "{{ key }}" : { "login" : "{{ value.login }}","prenom" : "{{ value.prenom }}","nom" : "{{ value.nom }}","mail" : "{{ value.mail }}","telephone" : "{{ value.telephone }}","is_staff" : "{{ value.is_staff }}","is_gestion" : "{{ value.is_gestion}}","is_admin" : "{{ value.is_admin }}"}, {% endfor %}}
    ajusteDonnees()
</script>

{% endblock body %}

base/templates/base/informations.html
{% extends 'base.html' %}

{% block body %}
{% include 'menu.html'%}
Informations
{% endblock body %}

base/templates/base/initialisation.html
{% extends 'base.html' %}

{% block body %}
{% include 'menu.html'%}
Page à faire. Pour réinitialiser le site (assez anecoditique)
{% endblock body %}

base/templates/base/menu.html
<header>
  {% if user.is_authenticated %} <div class="center">Bonjour {{ user.username }}</div>{% endif %}
  <nav class="menu">
        <ul>{% for item in menu %}
            <li class="menuli"><a href="{% url item.0 %}">{{ item.1 }}</a>                                                
            </li>{% endfor %}{% if user.is_authenticated %}
            <li> <a href="{% url 'reglages' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 -10 32 42">
                    <title>Réglages</title>
                    <path
                      d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
                    ></path>
                  </svg>
            </a></li>
            <li> <a href="{% url 'deconnexion' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 -10 32 42">
                    <title>Déconnexion</title>
                    <path
                      d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
                    ></path>
                    <path
                      d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
                    ></path>
                  </svg>
            </a></li>{% endif %}
        </ul>
    </nav>
    </header>

base/templates/base/modif_creneaux.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% csrf_token %}
{% include 'menu.html'%}
<BR><BR>Liste des créneaux disponibles : <BR><BR><BR>
<div id="liste_creneau">
</div>

<script src="{% static 'js/java_admin_modif.js' %}?=2" ></script> 
<script>
    supprime(0,false)
</script>
{% endblock body %}

base/templates/base/recuperation_login.html
{% extends 'base.html' %}

{% block body %}
<BR>
{% if msg %} <span class="cred"> {{ msg }}</span><BR><BR>
    <a href="{% url 'connexion' %}"> Retour à la page de connexion</a> <BR><BR>{% endif %}
    <fieldset class="formulaire">
        <legend>Formulaire de demande de login : </legend>
        <form method="POST" action="">
            {% csrf_token %}
            
            <div class="item_formulaire">
                <label for="id_mail">mail : </label>
                <input type="text" name="mail" maxlength="100" required id="id_mail">
            </div> 
            <input class="round" type="submit" value="Demande de login associé à ce mail"/>
    
        </form>
    </fieldset>

{% endblock body %}

base/templates/base/recuperation_password.html
{% extends 'base.html' %}

{% block body %}
<BR>
{% if msg %} <span class="cred"> {{ msg }}</span><BR><BR>
    <a href="{% url 'connexion' %}"> Retour à la page de connexion</a> <BR><BR>{% endif %}
    <fieldset class="formulaire">
        <legend>Formulaire de demande re réinitialisation de mot de passe : </legend>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="item_formulaire">
                <label for="id_login">login : </label>
                <input type="text" name="login" maxlength="100" required id="id_login">
            </div> 
            <div class="item_formulaire">
                <label for="id_mail">mail : </label>
                <input type="text" name="mail" maxlength="100" required id="id_mail">
            </div> 
            <input class="round" type="submit" value="Demande de réinitialisation de mot de passe"/>
    
        </form>
    </fieldset>

{% endblock body %}